"""drop allowlist and user_quota

Revision ID: 493e1402c7de
Revises: 8c440527796f
Create Date: 2026-09-20 21:47:00.209669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493e1402c7de'
down_revision: Union[str, None] = '8c440527796f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quota')
    op.drop_table('allowlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowlist',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('allowlist_pkey'))
    )
    op.create_table('user_quota',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('questions_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_quota_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_quota_pkey'))
    )
    # ### end Alembic commands ###
