"""llm_usage conversation_id nullable set null

Revision ID: 4c84b2b2def0
Revises: b4c5d6e7f8a9
Create Date: 2026-06-28 22:53:49.147074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c84b2b2def0'
down_revision: Union[str, None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_usage', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('llm_usage_conversation_id_fkey'), 'llm_usage', type_='foreignkey')
    op.create_foreign_key(None, 'llm_usage', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_usage', type_='foreignkey')
    op.create_foreign_key(op.f('llm_usage_conversation_id_fkey'), 'llm_usage', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('llm_usage', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
