"""add partner_profile_id to conversations and compatibility_score to birth_profiles

Revision ID: 6fb9f6c0ff16
Revises: 07634c8daf14
Create Date: 2026-06-28 12:18:36.542196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fb9f6c0ff16'
down_revision: Union[str, None] = '07634c8daf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birth_profiles', sa.Column('compatibility_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('conversations', sa.Column('partner_profile_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_partner_profile_id'), 'conversations', ['partner_profile_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'birth_profiles', ['partner_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_partner_profile_id'), table_name='conversations')
    op.drop_column('conversations', 'partner_profile_id')
    op.drop_column('birth_profiles', 'compatibility_score')
    # ### end Alembic commands ###
