"""add allowlist and user_quota

Revision ID: 8c440527796f
Revises: 4c84b2b2def0
Create Date: 2026-07-18 18:38:37.143693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c440527796f'
down_revision: Union[str, None] = '4c84b2b2def0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowlist',
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('user_quota',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questions_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quota')
    op.drop_table('allowlist')
    # ### end Alembic commands ###
